// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AreaPickerField: typeof import('./src/components/AreaPickerField/index.vue')['default']
    ButtonField: typeof import('./src/components/ButtonField/index.vue')['default']
    CalendarField: typeof import('./src/components/CalendarField/index.vue')['default']
    CheckboxField: typeof import('./src/components/CheckboxField/index.vue')['default']
    ContactField: typeof import('./src/components/ContactField/index.vue')['default']
    DatePickerField: typeof import('./src/components/DatePickerField/index.vue')['default']
    DateTimePickerField: typeof import('./src/components/DateTimePickerField/index.vue')['default']
    DesField: typeof import('./src/components/DesField/index.vue')['default']
    DividerField: typeof import('./src/components/DividerField/index.vue')['default']
    EmailField: typeof import('./src/components/EmailField/index.vue')['default']
    FileUploaderField: typeof import('./src/components/FileUploaderField/index.vue')['default']
    GenderField: typeof import('./src/components/GenderField/index.vue')['default']
    IdentityField: typeof import('./src/components/IdentityField/index.vue')['default']
    ImageUploaderField: typeof import('./src/components/ImageUploaderField/index.vue')['default']
    MarqueeField: typeof import('./src/components/MarqueeField/index.vue')['default']
    MultiRuleField: typeof import('./src/components/MultiRuleField/index.vue')['default']
    NameField: typeof import('./src/components/NameField/index.vue')['default']
    NoteField: typeof import('./src/components/NoteField/index.vue')['default']
    NumberField: typeof import('./src/components/NumberField/index.vue')['default']
    NutConfigProvider: typeof import('@nutui/nutui-taro')['ConfigProvider']
    NutDialog: typeof import('@nutui/nutui-taro')['Dialog']
    NutInput: typeof import('@nutui/nutui-taro')['Input']
    NutNoticebar: typeof import('@nutui/nutui-taro')['Noticebar']
    PhoneField: typeof import('./src/components/PhoneField/index.vue')['default']
    PickerField: typeof import('./src/components/PickerField/index.vue')['default']
    RadioField: typeof import('./src/components/RadioField/index.vue')['default']
    RatePickerField: typeof import('./src/components/RatePickerField/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RuleField: typeof import('./src/components/RuleField/index.vue')['default']
    SignField: typeof import('./src/components/SignField/index.vue')['default']
    TableField: typeof import('./src/components/TableField/index.vue')['default']
    Test: typeof import('./src/components/VideoField/test.vue')['default']
    TextareaField: typeof import('./src/components/TextareaField/index.vue')['default']
    TextField: typeof import('./src/components/TextField/index.vue')['default']
    TimePickerField: typeof import('./src/components/TimePickerField/index.vue')['default']
    VideoField: typeof import('./src/components/VideoField/index.vue')['default']
  }
}
